[package]
name = "esfpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib"]

[dependencies]
cxx = "1.0"
pest = "2.1"
pest_derive = "2.1"

[build-dependencies]
cxx-build = "1.0"
